Write tests
yiisoft/yii-queue pull request #174
Opened 2023-08-07 14:41 UTC by vladis84

| Q             | A
| ------------- | ---
| Is bugfix?    | ❌
| New feature?  | ❌
| Breaks BC?    | ❌
| Fixed issues  | comma-separated list of tickets # fixed by the PR, if any

2023-08-07 15:20 UTC, s1lver commented
Thanks! Still need to fix Style CI

2023-08-08 05:52 UTC, vjik requested changes

2023-08-08 05:52 UTC, vjik commented on tests/Unit/Command/ListenCommandTest.php
> +        $this->assertEquals('channel', $chanelArgument->getName());
```suggestion
        $channelArgument = $command->getNativeDefinition()->getArgument('channel');
        $this->assertEquals('channel', $channelArgument->getName());
```

2023-08-08 05:52 UTC, vjik commented on tests/Unit/Command/RunCommandTest.php
> +        $this->assertEquals('channel', $chanelArgument->getName());
```suggestion
        $channelArgument = $command->getNativeDefinition()->getArgument('channel');
        $this->assertEquals('channel', $channelArgument->getName());
```

2023-08-08 05:52 UTC, vjik commented on tests/Unit/SynchronousAdapterTest.php
> +        $this->expectException(\InvalidArgumentException::class);
```suggestion
        $this->expectException(\InvalidArgumentException::class);
        $this->expectExceptionMessage('This adapter IDs start with 0.');
```

2023-08-08 05:52 UTC, vjik commented on tests/Unit/SynchronousAdapterTest.php
> +        $this->expectException(\InvalidArgumentException::class);
```suggestion
        $this->expectException(\InvalidArgumentException::class);
        $this->expectExceptionMessage('There is no message with the given ID.');
```

2023-08-08 05:54 UTC, vjik approved these changes

2023-08-08 05:55 UTC, merged

2023-08-08 05:55 UTC, vjik commented
@vladis84 Thanks!