Rename yii-queue -> queue, Yii Queue -> Queue, Yii\Queue -> Queue
yiisoft/yii-queue pull request #184
Opened 2023-12-26 12:14 UTC by xepozz

| Q             | A
| ------------- | ---
| Is bugfix?    | ❌
| New feature?  | ✔️
| Breaks BC?    | ✔️

2023-12-26 15:55 UTC, samdark approved these changes

2023-12-26 15:55 UTC, samdark commented
https://github.com/yiisoft/yii-queue-amqp should be renamed as well.

2023-12-26 17:28 UTC, s1lver approved these changes

2024-01-04 06:31 UTC, rustamwin approved these changes

2024-01-05 17:52 UTC, vjik requested changes

2024-01-05 17:52 UTC, vjik commented on CHANGELOG.md
> +# Queue Change Log
```suggestion
# Yii Queue Change Log
```

We change package name to `yiisoft/queue` only, but pretty name keep as `Yii Queue`

2024-01-05 17:52 UTC, vjik commented on Makefile
> +export COMPOSE_PROJECT_NAME=queue
```suggestion
export COMPOSE_PROJECT_NAME=yii-queue
```

This name is used in globlal namespace. I think, better keep `yii-` prefix.

2024-01-05 17:52 UTC, vjik commented on tests/docker/docker-compose.yml
> +    container_name: queue-php
```suggestion
    container_name: yii-queue-php
```

It's used in global namespace. Better to keep `yii-` prefix.

2024-01-09 05:23 UTC, merged