Log exception on job fail
yiisoft/yii-queue pull request #57
Opened 2020-08-27 07:16 UTC by viktorprogger

| Q             | A
| ------------- | ---
| Is bugfix?    | ❌
| New feature?  | ✔️
| Breaks BC?    | ❌
| Fixed issues  | ❌

2020-08-27 13:40 UTC, samdark approved these changes

2020-08-29 13:25 UTC, xepozz requested changes

2020-08-29 13:25 UTC, xepozz commented on src/Exception/JobFailureException.php
> +        $messageText = "Processing of message #$messageId is stopped because of an exception:\n$error.";
```suggestion
        $messageText = "Processing of message #{$messageId} is stopped because of an exception:\n{$error}.";
```

2020-08-31 08:54 UTC, viktorprogger commented on src/Exception/JobFailureException.php
> +        $messageText = "Processing of message #$messageId is stopped because of an exception:\n$error.";
Why?

2020-09-02 09:06 UTC, viktorprogger commented on src/Exception/JobFailureException.php
> +        $messageText = "Processing of message #$messageId is stopped because of an exception:\n$error.";
Don't like curly braces :-1:

2020-09-03 07:56 UTC, thenotsoft approved these changes

2020-09-03 08:28 UTC, merged